# base image
FROM node:12.7.0-alpine as build

# set working directory
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY frontend/package.json /app/package.json
RUN npm install
RUN npm install react-scripts@3.0.1 -g
COPY ./frontend /app
EXPOSE 3000
# start app
RUN npm run build

# production
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

