FROM openjdk:8
ADD target/witi-1.0-SNAPSHOT.jar app.jar

RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/witi > application.properties'
RUN sh -c 'echo spring.datasource.username=root >> application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre1 >> application.properties'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
